# Generated by Django 4.1.6 on 2023-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('model_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(default='Unknown', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'mainWebsite_portfolio_model',
            },
        ),
    ]
