# Generated by Django 4.1.6 on 2023-04-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioModel',
        ),
    ]
