# Generated by Django 4.1.6 on 2023-04-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='one_line',
            new_name='oneLine',
        ),
    ]
