# Generated by Django 4.1.6 on 2023-04-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0006_account_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
