# Generated by Django 4.1.6 on 2023-04-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0007_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='oneLine',
        ),
    ]
